### ISSUE TITLE
1.8.8无法启动

### ISSUE THREAD

**Issue by Array-Cats** [EtherealAO/UmamusumeResponseAnalyzer#32]
[1]1.8.7无法正常更新到1.8.8（程序在报错后退出，%temp%文件夹会残留latest-UmamusumeResponseAnalyzer.exe）

[2]如果手动覆盖升级到1.8.8则在启动时报错。

两个操作的报错内容似乎是一致的，我就在下面贴出[2]的报错内容：

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 强制使用GitHub更新
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey , TValue , InsertionBehavior )
   at UmamusumeResponseAnalyzer.Config.Initialize()
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.Main(String[] args)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<Main>(String[] args)

[已退出进程，代码为 3762504530 (0xe0434352)]
```

**Comment by EtherealAO** [comment]
v1.8.9

**Comment by Array-Cats** [comment]
> v1.8.9

1.8.9如果从1.8.8手动覆盖后不删除AppData\Local\UmamusumeResponseAnalyzer里面的.config文件还是会产生相同的报错
