### ISSUE TITLE
在强制使用Github更新打开和关闭的两种情况下，更新数据文件都失败

### ISSUE THREAD

**Issue by 2455DD** [EtherealAO/UmamusumeResponseAnalyzer#43]
## 系统环境
OS: Windows 11 专业版 21H2

### `强制使用Github更新`选项关闭时
在初次下载后选择更新数据文件，出现以下错误
```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 )
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 )
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 , CancellationToken )
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter , ValueTask`1 , Int32 )
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter )
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.DownloadAssets(ProgressContext ctx, String instruction, String path)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<>c__DisplayClass5_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 96
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.Update(Boolean dataOnly)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.ShowMenu()
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.Main(String[] args)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<Main>(String[] args)
```

### `强制使用Github更新`选项打开后
打开`强制使用Github更新`选项后选择更新数据，出现问题如下图所示
![](https://s2.loli.net/2022/06/01/AezRNtU1r6Gspco.png)

**Comment by EtherealAO** [comment]
服务器忘开了，现在应该好了
