### ISSUE TITLE
无法更新数据文件

### ISSUE THREAD

**Issue by Array-Cats** [EtherealAO/UmamusumeResponseAnalyzer#7]
已确认电脑可以正常访问（https://github.com/EtherealAO/UmamusumeResponseAnalyzer），不需要使用梯子。
主程序挂上代理也出现相同的报错。

```
       正在从GitHub下载最新的events.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--:--
正在从GitHub下载最新的successevents.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--:--
           正在从GitHub下载最新的id.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--:--
    正在从GitHub下载最新的skilldata.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--:--
      正在从GitHub下载最新的name_cn.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--:--
        正在从GitHub下载最新的主程序文件 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% --:--:--

Unhandled exception. System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。 (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.DownloadAssets(ProgressContext ctx, String instruction, String path, String url)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<>c.<<Main>b__0_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 96
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.Main(String[] args)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<Main>(String[] args)

[已退出进程，代码为 3762504530 (0xe0434352)]
```

**Comment by EtherealAO** [comment]
github是github，被污染的是raw.githubusercontent.com不是github.com
